import type { Metadata } from "next";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Page",
  description: "Generated by create next app",
};


export default function Home() {
  return (
  <>
  </>
  );
}
